apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
  namespace: voting-app
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer