apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      microapp: voting-postgres
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-postgres
    spec:
      containers:
      - name: db-container
        image: postgres:15-alpine
        volumes:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            persistentVolumeClaim:
              claimName: db-pvc
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: voting-secret-postgres
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: voting-secret-postgres
                key: password
        ports:
          - containerPort: 5432
  