apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      microapp: voting-postgres
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-postgres
    spec:
      containers:
        - name: db-container
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
          - containerPort: 5432
          
      
  