apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      microapp: voting-redis
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name: redis-container
        image: redis:alpine	
        volumeMounts:
          - name: redis-storage
            mountPath: /data
        ports:
          - containerPort: 6379
          
      
  