apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      microapp: voting-redis
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-redis
    spec:
      containers:
        - name: redis-container
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
            mountPath: /data
      image: redis:alpine	
      ports:
      - containerPort: 6379
          
      
  