apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-redis
  template:
    metadata:
      labels:
        app: voting-redis
    spec:
      containers:
        - name: redis-container
          image: redis:alpine	
          ports:
          - containerPort: 6379
          
      
  