apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: result
      microapp: result-frontend
  template:
    metadata:
      labels:
        app2: result
        microapp: result-frontend
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result:latest
          ports:
          - containerPort: 80
          
      
  