apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
      microapp: voting-frontend
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-frontend
    spec:
      containers:
        - name: votefrontend
          image: dockersamples/examplevotingapp_vote:latest
          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: option_a
            - name: OPTION_B
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: option_b
          ports:
            - containerPort: 80
          
      
  