apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      app2: result
      microapp: voting-worker
  template:
    metadata:
      labels:
        app: voting
        microapp: voting-worker
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker:latest