apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      app2: result
      microapp: voting-worker
  template:
    metadata:
      labels:
        app: voting
        app2: result
        microapp: voting-worker
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker:latest
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: worker-config
                  key: redis_host
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: worker-config
                  key: postgres_host
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep -v grep | grep worker
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep -v grep | grep worker
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"