apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  env:
    - name: REDIS_HOST
      valueFrom:
        configMapKeyRef:
          name: worker-config
          key: redis_host
    - name: POSTGRES_HOST
      valueFrom:
        configMapKeyRef:
          name: worker-config
          key: postgres_host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting
      app2: result
      microapp: voting-worker
  template:
    metadata:
      labels:
        app: voting
        app2: result
        microapp: voting-worker
    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker:latest