apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-app
spec:
  type: ClusterIP
  selector:
    app: voting
    microapp: voting-redis
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      