apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: voting-app
spec:
  selector:
    app: result
  ports:
    - name: result-port
      port: 80
      targetPort: 80
      nodePort: 31000
      type: NodePort