apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: voting-app
spec:
  type: ClusterIP
  selector:
    app2: result
    microapp: result-frontend
  ports:
    - name: result-port
      port: 80
      targetPort: 80
      