apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting-app
spec:
  selector:
    app: voting
    microapp: voting-frontend
  ports:
    - name: voting-port
      port: 80
      targetPort: 80
      nodePort: 31000
      type: NodePort