apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: voting-app
spec:
  selector:
    app: voting
  ports:
    - name: worker-port
      port: 5555
      targetPort: 5555  
      type: ClusterIP